compressionLevel: mixed
enableStrictSsl: false

enableGlobalCache: false

yarnPath: .yarn/releases/yarn-4.0.0-rc.45.cjs

plugins:
  - checksum: fd862fe99cd107543cc4fef5ac49709268f5a99dbd4b60d1fc65dcb55ae0c86752e4494e9f7cb0b5481b73203b81c1ba0f529794f93d9fdc866458898a9863c1
    path: .yarn/plugins/@yarnpkg/plugin-yarnpnp2nix.cjs
    spec: "https://raw.githubusercontent.com/zarybnicky/yarnpnp2nix/master/plugin/dist/plugin-yarnpnp2nix.js"
